Rakefile, lib/http/response.rb
Discussion: https://groups.google.com/forum/#!topic/httprb/gqaMXeKIZbA
=> Delegate `Response#readpartial` to `#body`

CHANGES.md, http.gemspec, lib/http/chainable.rb, lib/http/client.rb, lib/http/headers.rb, lib/http/options.rb, lib/http/options/cookies.rb, lib/http/response.rb, spec/lib/http/options/merge_spec.rb, spec/lib/http/response_spec.rb
@httprb/owners if no objections - I would like to merge and cut release.
=> Add cookies support

spec/spec_helper.rb, spec/support/connection_reuse_shared.rb, spec/support/http_handling_shared.rb
=> Flag flaky tests and environments (i.e. JRuby on Travis)

.rubocop.yml, lib/http/connection.rb, lib/http/timeout/global.rb, lib/http/timeout/per_operation.rb, spec/lib/http/client_spec.rb
=> Enable exceptionless NIO when available

lib/http/timeout/null.rb
=> Rescue EOFError when using readpartial

lib/http/timeout/global.rb, spec/lib/http/client_spec.rb, spec/support/http_handling_shared.rb
https://github.com/httprb/http/commit/65900ad36e2ec47b1e1c5dce2e801fdf21637a8b#diff-0a8b9f11a32d37df2794313408d108c9L6
@tarcieri 
Not one of my finer moments
=> Fixed global timeout state persistence

.travis.yml
Should speed up builds if it works...
=> Use Travis's containerized build system

CHANGES.md
Some of the links in the changelog was not referencing the correct issues.
=> Updated links reference the right issues / PRs

lib/http/request/writer.rb
Concatenate the header and body prior to the write call. I believe most Rubies' String implementation will do this efficiently (paricularly with <<) and without excess copying.
Fewer system calls should be more efficient.
=> Write chunks of Enumerable bodies in a single system call

README.md
A few tiny changes to add syntax highlighting to the installation guide.
=> Add extra syntax highlight

lib/http/connection.rb
These make it easier to handle HTTP errors generically
=> Have IO exceptions reraise HTTP::ConnectionError (closes #303)

Gemfile, lib/http/chainable.rb, lib/http/client.rb, lib/http/connection.rb, lib/http/headers.rb, lib/http/mime_type.rb, lib/http/options.rb, lib/http/redirector.rb, lib/http/request.rb, lib/http/request/writer.rb, lib/http/response/body.rb, lib/http/response/status.rb, lib/http/timeout/global.rb, lib/http/timeout/per_operation.rb, lib/http/uri.rb
Lots of churn here around fail vs raise. Hopefully they don't change it again!
=> Upgrade to RuboCop 0.39.0

.travis.yml
- Only test master: this prevents duplicate builds for branches vs a PR
- Add whitespace
- Move language/sudo directives to the top of the file
=> Travis config cleanups

lib/http/response.rb, lib/http/response/body.rb, lib/http/response/inflater.rb, spec/lib/http/response/body_spec.rb
=> Fix Body initializer signature

spec/lib/http_spec.rb
The tests for large request bodies (which cover [this logic](https://github.com/httprb/http/blob/d7aa074d44c936bb1d82c72a87c4d538c31c56c4/lib/http/request/writer.rb#L98-L102)) in my opinion produces too many unnecessary specs.
<details>
<summary>Specs</summary>
```
with a large request body
with `.timeout(:null)`
with a 68000 body and 0 of fuzzing
returns a large body
when bytesize != length
returns a large body
with a 68000 body and 702 of fuzzing
returns a large body
when bytesize != length
returns a large body
with a 16000 body and 263 of fuzzing
returns a large body
when bytesize != length
returns a large body
with a 68000 body and 4 of fuzzing
returns a large body
when bytesize != length
returns a large body
with a 17000 body and 46 of fuzzing
returns a large body
when bytesize != …
```
=> Simplify test for sending large request bodies

lib/http/options.rb
- Added `reader_only` option to `def_option` and used it for `:features`, `:follow`, `:persistent`
- fixes #445
=> Fix warning method redefined on HTTP::Option

lib/http/chainable.rb
Small change, noticed the code comments didn't include some of the most recent features.
=> update code comments to include more recent features

lib/http/response/parser.rb, spec/lib/http/response/parser_spec.rb
..when they are returned in parts
Resolves: #589
=> Fix parser so it properly parses headers

lib/http/request.rb, spec/lib/http/redirector_spec.rb
=> Prevent bodies from being resubmitted when following unsafe redirects

LICENSE.txt
Range of years not in sync with that of the README
=> Update license year range

http.gemspec, spec/lib/http/response/parser_spec.rb
Hi, can we have the addressable gem updated?
Thanks!
=> Update addressable because of CVE-2021-32740

lib/http/response.rb
=> Fix cookies extraction

lib/http/timeout/global.rb, lib/http/timeout/per_operation.rb
=> Revert DNS resolving feature.

CHANGES.md
Fixes: https://github.com/httprb/http/issues/700
=> Update changelog with breaking change note

lib/http/features/instrumentation.rb, spec/lib/http/features/instrumentation_spec.rb
This seems like a missing piece in the instrumentation feature.
=> Let the instrumenter log exceptions too

http.gemspec
Clean-up gemspec a bit.
The plan is to eventually switch to [Zeitwerk](https://github.com/fxn/zeitwerk) for auto-loading.
=> chore: Cleanup and update gemspec
