httprb/http

lib/http/errors.rb
lib/http/headers.rb
spec/lib/http/headers_spec.rb

Disallows to pass invalid header field names like:
- `"Foo Bar"` (using spaces)
- `"  Foo-Bar"` (leading and/or tailing spaces)
- `"Foo:Bar"` (using separator field)
See http://tools.ietf.org/html/rfc7230#section-3.2 and specifically `field-name` syntax for details.

Fail upon invalid HTTP header field name

---

.rubocop.yml
Gemfile
lib/http/client.rb
spec/lib/http/client_spec.rb
spec/spec_helper.rb
spec/support/create_certs.rb
spec/support/dummy_server.rb
spec/support/servers/config.rb

Right now http.rb doesn't run the post certificate check after connecting, meaning a mismatch host doesn't raise an error like it normally would.
cc @tarcieri

Ensure we verify SSL certificate identify after connecting

---

lib/http/client.rb

Since `SSLSocket` wraps a socket, when you call `close` you're calling `socket.flush` (on SSLSocket) and then `socket.sysclose` which goes to https://www.omniref.com/ruby/1.9.3.484/symbols/OpenSSL::SSL::SSLSocket/sysclose. That will free up all the SSL bits, but it doesn't close the underlying socket that was passed to SSLSocket. Adding `sync_close` will make sure that it actually does that to avoid leaks.

Set sync_close when available to avoid leaking sockets

---

.rubocop.yml
Gemfile
lib/http/client.rb
spec/http/client_spec.rb
spec/spec_helper.rb
spec/support/black_hole.rb
spec/support/create_certs.rb
spec/support/dummy_server.rb
spec/support/dummy_server/servlet.rb
spec/support/servers/config.rb
spec/support/servers/runner.rb

Here is a very naive backport of @zanker's SSL host verification. I would like to have this in a 0.6.x version then add this patched version to https://github.com/rubysec/ruby-advisory-db/blob/master/gems/http/CVE-2015-1828.yml too.
Tell me if I can do anything else about this.

Backport #180 (CVE-2015-1828) in 0-6-stable branch

---

lib/http/client.rb

For our tests, we also want to close the connection to get a clean slate, but also since it's a pattern that's repeated, rather just make it a method.

Add a close API and us that instead for the client

---

lib/http/connection.rb
lib/http/response/body.rb
spec/support/connection_reuse_shared.rb

Fun one that was due to a typo :(
The sequence IDs are unnecessary, because in real conditions if you try and request while it's still pending a response it will just simply error.

Fixed tests to avoid mixed responses with Keep Alive

---

lib/http/client.rb
lib/http/connection.rb
lib/http/options.rb
spec/lib/http/client_spec.rb
spec/lib/http/options/merge_spec.rb
spec/support/connection_reuse_shared.rb

This is in net-http-persistent too and as far as I can tell it's kind of necessary.
Adds a timeout so if the connection isn't used for more than X seconds, it automatically restarts it.

Added Keep-Alive timeouts to auto reset connections

---

lib/http.rb
lib/http/client.rb
lib/http/connection.rb
lib/http/errors.rb
lib/http/options.rb
lib/http/timeout/global.rb
lib/http/timeout/null.rb
lib/http/timeout/per_operation.rb
spec/lib/http/client_spec.rb
spec/lib/http/options/merge_spec.rb
spec/support/dummy_server/servlet.rb
spec/support/http_handling_shared.rb

This is mildly crazy. Basically this adds three sets of timeouts
Null, which is just what there is today (nothing)
Per operation, which is what you see in things like Net::HTTP, Excon where the timeout is per operation
Global, which sets an allocation of how much time can be used and uses it up as the request goes. Ensuring a request can never run longer than the set time.
Getting DNS to have a customizable timeout is awful though, which is why there's a lot of extra code for doing `connect` (mostly cribbed from Tony's code). My inclination, would be to just wrap it in `Timeout.timeout` since that can be done more safely than relying on all the Ruby internals to handle the DNS/open timeouts properly. And it's safer, any thoughts on that?

Added configurable connection timeouts

---

lib/http/connection.rb
lib/http/options.rb
lib/http/timeout/null.rb
spec/lib/http/client_spec.rb
spec/lib/http/options/merge_spec.rb
spec/support/ssl_helper.rb

Makes it a bit easier to configure things for SSL. As an advantage, this gives people more secure SSL configuration by default via the `DEFAULT_PARAMS` in https://github.com/ruby/openssl/blob/master/lib/openssl/ssl.rb#L25.
Personally, I'm not sure how much sense allowing `ssl_context` makes, since I wasn't aware there was really competition for other SSL gems in Ruby. Although I defer to @tarcieri on that.

Added SSL config via the ssl param instead of requiring context passing

---

lib/http/chainable.rb
lib/http/client.rb
lib/http/connection.rb
lib/http/options.rb
lib/http/redirector.rb
spec/lib/http/client_spec.rb
spec/lib/http/redirector_spec.rb
spec/lib/http_spec.rb

Refactor redirector logic

---

.rubocop.yml
lib/http/client.rb
spec/support/http_handling_shared.rb

Thoughts? This isn't strictly necessary, as the chance of this happening is very very small. It is still a chance though.
Normally, `Timeout.timeout` raises an exception and kills the block and everything is handy dandy. In rare situations, it will raise and then kill execution while the `rescue` block executes (see https://github.com/mperham/connection_pool/pull/67 for more info).
This adds an extra layer of protection, where if we run into that, we reset the connection anyway.

Add an extra set of state tracking for Timeout.timeout edge cases

---

lib/http/timeout/global.rb
lib/http/timeout/per_operation.rb
spec/lib/http/client_spec.rb
spec/support/http_handling_shared.rb

Unfortunately, getting a pure solution to timeouts is essentially impossible without rewriting the entire stack yourself. Which I might actually do for fun later, but for the time being. This is the simplest way of getting a connect timeout :(

Use Timeout.timeout for TCP connection

---

lib/http/timeout/global.rb
lib/http/timeout/per_operation.rb

@tarcieri going to merge on green just as a fyi
Looking at Excon's code, they only time they don't raise is on `read will block` and not on writes (until my change) where I technically broke it.
I'm still going to add this as a just in case, since the Ruby docs mention it.

Make sure we catch WaitWritable for SSL

---

http.gemspec
lib/http/client.rb
lib/http/connection.rb
lib/http/request.rb
lib/http/uri.rb
spec/lib/http/client_spec.rb
spec/lib/http/request_spec.rb
spec/lib/http_spec.rb

Add support for non-ascii URIs

---

CHANGES.md
lib/http/chainable.rb
lib/http/client.rb
spec/lib/http_spec.rb

Example Usage:
==============
``` ruby
def keys(users)
HTTP.persistent("https://github.com") do |http|
users.map { |u| http.get("/#{u}.keys").to_s }
end
end
```
Resolves #200

Allow call `#persistent` with block

---

.rubocop.yml
lib/http/client.rb
lib/http/connection.rb
lib/http/request.rb
lib/http/request/writer.rb
spec/lib/http_spec.rb

This is pretty rough but I wanted to see if this looks like I'm at all going in the right direction. I added a failing test which now passes, so I think this is at least functional. Any feedback on what I need to do to get this into a mergable state would be great.
Connecting to https servers through a http proxy requires sending a CONNECT request to the proxy to setup a tunnel, then performing a normal https request through that tunnel. This PR adds the code to send that CONNECT request before continuing with the normal request.

First attempt at supporting https connections through proxy

---

lib/http/connection.rb
lib/http/timeout/global.rb
lib/http/version.rb
spec/support/http_handling_shared.rb

:(
Hat tip to @RickCSong for spotting this.

Reset global timeouts after the request finishes

---

README.md

@ixti the docs on timeout aren't quite right (namely they need the type of timeout). Celluloid::IO works again, since the `respond_to? :sync_close=` change was made. Although @tarcieri should tag a new celluloid-io that has that fix in!

Updated documentation on timeouts

---

lib/http/request.rb

I think this fixes #217 the problem seemed to be that @uri.port was blank so a port wasn't being specified if the default port was used. Seems like this code should be using the helper methods anyway.

Make sure port number isn't blank for proxy connect

---

README.md

Being able to reuse HTTP connection is a very valuable feature. It's documented in code, but not in the documentation: even an experimented source reader as I am missed it and I had to bother guys on the google group.
A simple sample to say "I exist" will help a lot :)

Add Http.persistent sample in Readme.md

---

lib/http/timeout/null.rb
lib/http/timeout/per_operation.rb

CodeClimate highlighted some duplication in the Timeout::PerOperation class. This change eliminates the code duplication.

a DRY change, addressing code duplication in http/timeout/per_operation

---

CHANGES.md
lib/http/connection.rb
lib/http/timeout/global.rb
lib/http/timeout/per_operation.rb
lib/http/version.rb

:(
So in true Ruby tradition. Exceptionless NIO has no real documentation, I misunderstood a patch I was reading originally and thought it returned `:eof` on EOF. Apparently it returns nil (super obvious right?)
I just looked again and found: https://bugs.ruby-lang.org/issues/11358 and reading _that_ patch shows returning a nil is correct.
This won't happen in general use, but it's still not great.

Fixed exceptionless NIO handling for EOF

---

lib/http/request/writer.rb

Remove usage of ActiveSupport's #present? method

---

Rakefile
lib/http/timeout/global.rb

The main motivation for this change is because JRuby 9000 supports exceptionless non-blocking I/O for `TCPSockets` but *not* for` SSLSockets`. Both accept the `:exception => false` syntax, so it's harmless to pass it to SSLSockets even though they silently ignore it. Unfortunately, even with `:exception => false` JRuby 9000 still throws `IO::WaitReadable`/`IO::WaitWritable`, so until that's fixed upstream we need to handle it.
This change also adds handling non-blocking reads during writes and writes during reads, which is necessary for SSLSockets to work correctly on all platforms (i.e. an SSL handshake might require performing a read for a write to complete, or vice versa)
I'm pleased with the result in as much as it provides a single approach which covers all cases (`#perform_io`).

Unified exceptional/exceptionless non-blocking I/O

---

CHANGES.md
Gemfile
lib/http/chainable.rb
lib/http/connection.rb
lib/http/headers.rb
lib/http/options.rb
lib/http/request.rb
lib/http/response.rb
lib/http/response/parser.rb
lib/http/response/status.rb
spec/lib/http/options_spec.rb
spec/lib/http/response/status_spec.rb
spec/lib/http_spec.rb

I'd still like to go forward with a 1.0 release (and at least blog about it)
This removes all deprecations and documents replacements where applicable.

Remove all deprecations (closes #208)

---

spec/support/http_handling_shared.rb

This test passes sporadically on JRuby and is causing the test suite to fail sporadically.
Lacking time to investigate I flagged it as pending on JRuby so the test suite passes consistently.
This might be a sign of deeper problems, but I have a pretty bad track record with JRuby, CI, and specs related to timeouts.
/cc @zanker

Flag flaky timeout spec as pending on JRuby

---

README.md

The timeout backend is broken/nonexistent. Until it's implemented, we shouldn't advertise Celluloid::IO support.
Users of Celluloid who want parallel requests can use a thread pool.

Remove Celluloid::IO docs

---

lib/http/connection.rb
lib/http/errors.rb
lib/http/response/status.rb
spec/lib/http/request/writer_spec.rb
spec/lib/http/response/status_spec.rb
spec/lib/http_spec.rb
spec/support/connection_reuse_shared.rb
spec/support/http_handling_shared.rb

Hide implementation details

---

lib/http/chainable.rb
lib/http/client.rb
lib/http/options.rb
lib/http/response.rb
lib/http/response/body.rb
spec/lib/http/client_spec.rb
spec/lib/http/options/merge_spec.rb
spec/lib/http/redirector_spec.rb
spec/lib/http/response/body_spec.rb
spec/lib/http/response_spec.rb
spec/lib/http_spec.rb
spec/support/dummy_server/servlet.rb

Add encoding option

---

lib/http/response/body.rb

Set default HTTP::Response::Body encoding to Encoding::BINARY

---

lib/http/request/writer.rb

This change tries to avoid a pathological case with Nagle's algorithm where two small writes that would fit in a single TCP packet are performed in a row (headers and body).
Instead, it tries to perform a single write if possible.
cc @nerdrew @zanker

Send headers and body in one write if possible

---

.rubocop.yml
lib/http/timeout/global.rb
lib/http/timeout/null.rb
lib/http/timeout/per_operation.rb

IO.select is an expensive call, because it has to build an fd_set (large bitfield) from an array each time we invoke it.
We're just interested in IO readiness, so on Ruby 2.0+ we can use the io/wait API instead, which adds wait_readable/wait_writable to IO objects.
cc @zanker @nerdrew

Use io/wait on platforms where it's available

---

README.md

Hello 👻
It wasn't until I dug deep into the source code that I realised there was a way to fire multiple requests over the same connection *outside of a block*. I thought that this deserves a mention in `README`.
I've used the `c` variable name because:
- it actually refers to an instance of `Client`
- semantically it is best to call it a connection
- the actual name is irrelevant and can be anything and I wanted it to get out of the way
Hope this helps!

Document HTTP.persistent without a block in README

---

lib/http/redirector.rb

Otherwise redirect following will not work on persistent connections:
``` ruby
HTTP.follow.persistent("https://play.google.com") do |http|
http.get("https://play.google.com/store/apps/")
end
```
fails with obvious state error:
```
HTTP::StateError: Tried to send a request while one is pending already. Make sure you read off the body.
from /home/ixti/.gem/ruby/2.3.0/gems/http-1.0.1/lib/http/connection.rb:63:in `send_request'
```

Flush response before following redirect

---

.rubocop.yml
Gemfile
lib/http.rb
lib/http/chainable.rb
lib/http/client.rb
lib/http/connection.rb
lib/http/headers.rb
lib/http/headers/known.rb
lib/http/request.rb
lib/http/request/writer.rb
lib/http/response.rb
lib/http/response/body.rb
lib/http/response/parser.rb
lib/http/response/status.rb
lib/http/timeout/global.rb
lib/http/timeout/null.rb
lib/http/uri.rb
lib/http/version.rb
spec/lib/http/client_spec.rb
spec/lib/http/headers_spec.rb
spec/lib/http/response/status_spec.rb
spec/lib/http/response_spec.rb
spec/lib/http_spec.rb
spec/spec_helper.rb
spec/support/servers/runner.rb
spec/support/ssl_helper.rb

Includes a lot more cops for frozen string literals and constants which seem nice, particularly on Ruby 2.3+

Update to RuboCop 0.36

---

lib/http/timeout/per_operation.rb

I started out reverting the changes to this file back to the version
@ixti bisected as being the last good one.
I left in the *actual* code that replaced IO.select with io/wait. And
I seem to have come upon the same thing @ixti did here:
https://github.com/httprb/http/commit/9e1e100d89e365600010859ea8c87400a766c29b
I'll have to check the behavior on JRuby, and am uncertain what sequence
of events causes the rescue_readable call to be an issue, but I think this
both lets us keep io/wait and at least has the same semantics as before.

Remove exception wrappers from per_operation.rb

---

lib/http/content_type.rb
lib/http/response/body.rb

Validate encoding in `Content-Type` before `force_encoding` response contents.

fixes #312

---

lib/http/headers.rb

In response to https://github.com/httprb/http/issues/317#issuecomment-197042971

Reduce amount of objects upon headers normalization

---

.rubocop.yml
lib/http/timeout/global.rb
lib/http/timeout/null.rb
lib/http/timeout/per_operation.rb

Merging this directly into 1-x-stable so it doesn't interfere with #319

Fix timeout regression

---

lib/http/timeout/per_operation.rb

I have tried the repro case from #298 from this and this appears to
fix the problem.
Not sure why: the intended semantics appear to be equivalent. Possibly
a MRI bug that was fixed in 2.3?

Revert to IO.select for PerOperation timeouts (fixes #298)

---

lib/http/chainable.rb
lib/http/uri.rb
spec/lib/http/uri_spec.rb

The Addressable gem has been the source of a number of bugs and performance problems (e.g. #206, #297, #323)
Perhaps in the future it might be worth avoiding using it where `::URI` would suffice, or getting rid of it entirely, but as things stand `Addressable::URI` is the parent class for `HTTP::URI`, which prevents us from doing that without making a breaking release of the library.
This replaces inheritance with object composition: `Forwardable` is used to delegate an explicit set of methods to `Addressable::URI`. This should make it easier to work around Addressable bugs or
potentially even use `::URI` as the internal representation when URIs are simple enough.

Use object composition rather than inheritance for HTTP::URI

---

lib/http/chainable.rb
lib/http/client.rb
lib/http/connection.rb
lib/http/request.rb
lib/http/response.rb

Note: Just throwing this idea out there -- I implemented these changes for my own use case, but I'm happy to rework the implementation if it's not deemed suitable for merging. Let me know.
Some proxies accept custom headers, for things like switching IPs, excluding certain IPs, or specifying custom behaviors (like retrying requests when certain codes are returned). Over normal HTTP, these can be sent along with the rest of your headers, and the proxy will filter the headers before passing the request along. Likewise, the proxy might inject a custom header into the response (such as one indicating the IP your request was passed through).
**However**, everything changes over a secured connection. When connecting to a proxy over HTTPS, this gem makes use of HTTP tunneling via the 'CONNECT' …

Support custom CONNECT headers (both request and response) during HTTPS proxy requests

---

lib/http/response/status.rb
lib/http/response/status/reasons.rb
spec/lib/http/response/status_spec.rb

* Break status codes up by type
* Add status boolean helper methods to check status types.
example usage:
```
HTTP.get('http://google.com').status.informational?
HTTP.get('http://google.com').status.success?
HTTP.get('http://google.com').status.redirect?
HTTP.get('http://google.com').status.client_error?
HTTP.get('http://google.com').status.server_error?
```
returns true or false, depending on status code type

Separate status codes by type and add helper methods to check status

---

lib/http/response/status.rb
lib/http/response/status/reasons.rb

Remove extra constants from status reasons

---

lib/http/request/writer.rb
spec/lib/http_spec.rb

This doesn't actually fail in our tests, because the test server we use apparently is broken too. I'm adding it more for posterity than it helps prevent regressions. I tested it against Passenger where it does fix it though!
We send `Content-Length` using `bytesize`, but we sliced the buffers using `length`. When those don't match up, things blow up because we send corrupted data. This would only happen if you're sending enough data that it can't be buffered into one `write` call.

Always use byte methods when writing/slicing the write buffer

---

http.gemspec

Seems we never captured this before...

Set required Ruby version to 2.0 in gemspec

---

Gemfile

- Remove celluloid-io: we don't use it anymore
- Remove Ruby 1.9isms
- Add more :require => false

Cleanup dev dependencies

---

lib/http/client.rb
lib/http/connection.rb

I found out that sometimes you can get this error when using the gem:
from /.../gems/http-2.0.1/lib/http.rb:8:in  `<top (required)>'
from /.../gems/http-2.0.1/lib/http.rb:8:in  `require'
from /.../gems/http-2.0.1/lib/http/client.rb:7:in  `<top (required)>'
from /.../gems/http-2.0.1/lib/http/client.rb:7:in  `require'
from /.../gems/http-2.0.1/lib/http/connection.rb:4:in  `<top (required)>'
from /.../gems/http-2.0.1/lib/http/connection.rb:4:in  `require'
The problem was that `http.rb` was requiring `http/client.rb` that at the same time was requiring `http/connection.rb` which was requiring `http/client.rb` again.
I think that in general is not very good to have a cycle like this in the dependency graph of the code, so I decided to remove that dependency by moving the constants `KEEP_ALIVE` …

Avoid a dependency cycle between Client and Connection classes.

---

Gemfile

Unfortunately certificate_authority depends on this.
This ensures we use a version that works on all Rubies we support.

Lock to ActiveModel 4.x

---

lib/http/response.rb
lib/http/response/body.rb
spec/lib/http/response/body_spec.rb
spec/lib/http/response_spec.rb

The [Down](https://github.com/janko-m/down) gem provides the ability to wrap anything that streams chunks into an IO object. I want to add support for HTTP.rb to Down so that you can do the following:
```rb
response = HTTP.any.request.options.get("http://example.com")
remote_file = Down.open(response)
remote_file # IO object which downloads only how much it needs
```
For this I need to be able to access the connection through the response object, so that I can close the connection if either the downloading finishes or user calls `remote_file.close`.

Add HTTP::Response#connection

---

lib/http/chainable.rb

A minor typo makes it very difficult to parse the docs for the `#timeout` method: http://www.rubydoc.info/github/httprb/http/HTTP/Chainable#timeout-instance_method
This just correct the `@overload` declarations and adds a tiny bit more info.

Fixing up the #timeout docs on Chainable

---

.rubocop.yml
lib/http/chainable.rb
lib/http/client.rb
lib/http/feature.rb
lib/http/features/auto_deflate.rb
lib/http/features/auto_inflate.rb
lib/http/headers/known.rb
lib/http/options.rb
lib/http/response.rb
lib/http/response/body.rb
lib/http/response/inflater.rb
spec/lib/http/features/auto_deflate_spec.rb
spec/lib/http/features/auto_inflate_spec.rb
spec/lib/http/options/features_spec.rb
spec/lib/http/options/merge_spec.rb
spec/lib/http/response/body_spec.rb
spec/lib/http_spec.rb
spec/support/dummy_server/servlet.rb

Hi,
I implemented gzip/inflate decompression. It resolves #113.
Before:
```
HTTP.headers('Accept-Encoding' => 'gzip').get("https://github.com").to_s[0,12]
=> "\u001F\x8B\b\u0000\u0000\u0000\u0000\u0000\u0000\u0003\xED]"
```
After:
```
HTTP.headers('Accept-Encoding' => 'gzip').get("https://github.com").to_s[0,12]
=> "\n\n\n<!DOCTYPE"
```
Please, let me know if I need to change something here.

Support for Gzip/Inflate

---

.travis.yml
Gemfile
README.md
lib/http/request.rb
spec/spec_helper.rb
spec/support/http_handling_shared.rb

Add REPORT as valid HTTP verb

---

.travis.yml
Rakefile

Don't redundantly run RuboCop on every Ruby under the sun.
This will inadvertently fix the build as well. Woohoo! (Ok, not actually inadvertently)

Only run RuboCop on 2.4.0

---

.rubocop.yml
lib/http/chainable.rb
lib/http/client.rb
lib/http/feature.rb
lib/http/options.rb
lib/http/redirector.rb
lib/http/timeout/null.rb
spec/support/dummy_server.rb

We should start favoring keyword arguments
See: https://github.com/httprb/http/pull/368#issuecomment-278060919

Enable the Style/OptionHash cop in RuboCop

---

lib/http/uri.rb
spec/lib/http/uri_spec.rb

Add URI#dup method to fix a bug with shared internal instance variables

---

lib/http/request.rb
spec/lib/http/request_spec.rb

When redirecting on `http://localhost:<port>` URLs, the Host will be correctly set to `http://localhost:<port>` on the initial request, but on following the redirect the port is lost, because we're only assigning the host.
Therefore when we initialize the follow-up request object we de-assign "Host", and let HTTP::Request set it in the same way as it is set on the initial request.
Since we're stubbing redirects at the moment, I didn't know how to write a test for this.

Let Host be automatically inferred on redirects

---

http.gemspec
lib/http/client.rb
lib/http/request.rb
lib/http/request/body.rb
lib/http/request/writer.rb
spec/lib/http/client_spec.rb
spec/lib/http/request/writer_spec.rb
spec/spec_helper.rb
spec/support/fakeio.rb

This change adds the ability to stream content of an IO object (an object that responds to #read) into the request body. This is convenient when you want to send large amounts of data as the request body, but you don't want to load all of it into memory.
```rb
HTTP.post("http://example.org/upload", body: File.open("video.mp4"))
HTTP.post("http://example.org/upload", body: StringIO.new("file data"))
```
It was already possible to send the request body in chunks by passing an Enumerable to `:body`, but that can (and should) only be used for making "Transfer-Encoding: chunked" requests.
This will also allow us to extend form_data.rb to stream the multipart-encoded request, instead having to load the whole body into memory before writing it to the socket.

Enable request body streaming with an IO object

---

lib/http/response/body.rb
spec/lib/http/response/body_spec.rb

MRI will return content read from the socket in the ASCII-8BIT (binary) encoding, whereas JRuby will return it in the UTF-8 encoding. In whichever encoding the body is retrieved, we want to force its encoding to the one specified (charset response header if present, otherwise binary). This is already the behaviour in `Response::Body#to_s`, we just extend it to `Response::Body#readpartial` as well.
Fixes #413.

Return response body chunks in specified encoding

---

.travis.yml

This PR updates the CI matrix to use latest JRuby.
http://jruby.org/2017/06/15/jruby-9-1-12-0.html
It also loses the "hold still at 1.14.x of Bundler".

Travis: jruby-9.1.12.0, newer Bundler, RubyGems

---

lib/http/request/writer.rb
spec/lib/http/request/writer_spec.rb

Writing to the TCP socket can also fail with various exceptions, just like when opening or reading from it. For example, it happened to me that an `Errno::EPIPE` exceptions was raised during file upload, presumably because the server closed the connection early.
In order to be consistent with re-raising low-level exceptions as `HTTP::ConnectionError` when opening or reading from the TCP socket, we also add the same behaviour when writing to the socket.
Closes #430

Raise ConnectionError when writing to socket fails

---

lib/http/request.rb
lib/http/request/body.rb
spec/lib/http/request/body_spec.rb

This makes it possible to access the original body object, which [httplog](https://github.com/trusche/httplog) needs to log request bodies.
Related to #437.

Add Request::Body#source

---

lib/http/chainable.rb
lib/http/timeout/global.rb
lib/http/timeout/per_operation.rb
spec/lib/http_spec.rb
spec/support/http_handling_shared.rb

- `.timeout(<Numeric>)` sets a global timeout value.
- `.timeout(connect: x, write: y, read: z)` sets per operation timeouts.
The previous style: `.timeout(:global|:per_operation, hash_of_options)` doesn't work anymore.
fixes #444

Simplify setting a timeout

---

lib/http/connection.rb
lib/http/timeout/global.rb
lib/http/timeout/null.rb
lib/http/timeout/per_operation.rb

Currently for each chunk read from the socket a new string is being allocated. This is not necessary, because we're feeding that string object into the HTTP parser and never using it again.
So we initialize a buffer string and pass it in when reading chunks. This will make each chunk be read into the same buffer object, no new string will be allocated in that operation.
When profiling download of a 18MB file, before this change there was 48MB of strings being allocated, and after this change it's about 18MB. This is **more than 50%** reduction in memory allocation.

Reduce memory usage when reading response body

---

lib/http/response/body.rb

From Eric Wong (Ruby & Unicorn committer) in "[String memory use reduction techniques](https://ruby-talk.trydiscourse.com/t/psa-string-memory-use-reduction-techniques/74477)"
> String#clear exists since Ruby 1.9.1 and immediately releases memory allocated from malloc(3). I use this to reduce memory pressure and improve locality when working with large buffers.
An example of how such clearing of used string objects reduced memory usage in `open-uri`: https://bugs.ruby-lang.org/issues/14320
I tested the memory usage using `MemoryProfiler`, and it did show **50% reduction** in allocated memory:
```rb
require "http"
require "memory_profiler"
MemoryProfiler.report do
HTTP.get("https://upload.wikimedia.org/wikipedia/commons/3/36/Hopetoun_falls.jpg").to_s
end.pretty_print
```
Now, I'm aware that …

Deallocate temporary strings in Response::Body#to_s

---

http.gemspec

The gemspec included the pre-release of `http-form_data` at the moment the major version wasn't out yet, and we forgot to remove it once it was released. This PR takes care of that.

Remove http-form_data pre-release from gemspec

---

lib/http/client.rb
lib/http/uri.rb
spec/lib/http/client_spec.rb

Expose `HTTP::URI#query_values` & `HTTP::URI#query_values=` which delegate to the underlying `Addressable::URI` instead of using Addressable's `form_encode` method.
fixes #449

Fix query string building for string with newlines

---

lib/http/features/auto_deflate.rb

On aa7c688 `HTTP::Features::AutoDeflate` got a major refactoring, delegating most of the work to their own classes (`GzippedBody` & `DeflatedBody`), but a branch preventing a wrong value passed to #deflated_body (`headers` params) was left behind.
Currently the removed code will never be executed because the values of the property `method` are enforced on the `initializer` (accepting only gzip & deflated):
https://github.com/httprb/http/blob/b3ac5564eeb3efac936e2e919329a48755c61ad3/lib/http/features/auto_deflate.rb#L11-L17

Removing unreacheable code in HTTP::Features::AutoDeflate

---

lib/http/connection.rb

This simplifies the implementation of `HTTP::Connection#read_headers!`, the behaviour should be preserved.

Simplify HTTP::Connection#read_headers!

---

lib/http/connection.rb
lib/http/response/parser.rb

Fixes https://github.com/httprb/http/issues/384.
```rb
response = HTTP.get('http://www.rubydoc.info/github/httprb/http')
5.times { puts response.body.readpartial(10).length }
```
I didn't find an easy way to write specs for this, because everything is stubbed :stuck_out_tongue:

Fix #readpartial not respecting max length argument

---

lib/http/chainable.rb
lib/http/client.rb

It would sometimes be handy to have a public method that returns a request object so that we can modify it and/or pass around and then use `perform` on it. 
Please take a look and if you find the idea is OK I will add specs etc.

Extract HTTP::Client#build_request method

---

lib/http/request.rb
spec/lib/http_spec.rb

HTTP.get doesn't allow to make requests to urls with two leading slashes (e.g. `https://google.com//`).
See previous discussion at #389.
Steps to reproduce
===
```ruby
HTTP.get("https://google.com//")
#Addressable::URI::InvalidURIError: Cannot have a path with two leading slashes without anauthority set: '//'
```
Now it's possible to use such urls.

Fix HTTP::Request#headline to allow two leading slashes in path

---

lib/http/connection.rb
lib/http/response/parser.rb
spec/lib/http/connection_spec.rb

800c5815 broke `readpartial` method: it returns same chunk twice :(
Ref #454.
BTW it's a good example of that public accessors in behavior (non-data) classes are harmful.

Fix broken HTTP::Connection#readpartial

---

lib/http/request/body.rb
spec/lib/http/request/body_spec.rb

Webmock triggers `body.each` twice upon inital request recording:
1. to perform request
2. to record request data into webmock request registry
But even without WebMock, generally Body#each must be replayable IMO.

Rewind IO-alike request body after it was consumed.

---

.rubocop.yml
lib/http/request/writer.rb
spec/lib/http/request/writer_spec.rb

HTTP servers typically wait until the whole request body has been received before sending the response. However, some servers might send out a response early, before they've read the whole request body. For example, they might detect the request headers were invalid, and they want to tell that to the client immediately.
For example, sending a large request to http://google.com will return an early `400 Bad Request` response. In this case http.rb will raise an `Errno::EPIPE` exception (wrapped in a `HTTP::ConnectionError`), because it tried to write to the socket but it couldn't because the server closed its end. However, the server still returned a valid response, so it's not really erroneous behaviour (e.g. curl doesn't print any errors in the same situations).
```rb …
```

Handle early responses

---

README.md

People seem to have trouble finding it

README.md: Add more obvious 'Documentation' link

---

lib/http/client.rb
lib/http/feature.rb
lib/http/features/auto_deflate.rb
lib/http/features/auto_inflate.rb
lib/http/request.rb
lib/http/response.rb
spec/lib/http/features/auto_inflate_spec.rb

This makes `HTTP::Client`, `Request` and `Response` unaware of the implementation details behind inflating and deflating stream bodies. Instead, the client iterates over all enabled features on request and response, calling `#wrap_request` or `#wrap_response`, which is expected to return the Request or Response as-is if nothing should be done, or returns a new Request or Response object after having done whatever transformation the feature requires.
Related to #478 (and all the issues linked therein), this also provides a clean way to implement more features, like logging/instrumentation, caching, etc... In fact, several existing http.rb features could be probably be refactored into this style and clean up the codebase (proxy, json parsing, cookies, redirects...)
This pattern also avoids …

Refactor AutoInflate/Deflate into generic features

---

.travis.yml
lib/http/chainable.rb

Currently, if default_options are set, they are respected for methods such as #via or #timeout but not with a simple request.
Let me know if this would make sense, or if the current implementation is intentional!
cc @zanker HI ZANKER :)

Respect default_options for HTTP::Chainable#request and HTTP::Chainable#build_request

---

lib/http/client.rb
lib/http/features/auto_deflate.rb
spec/lib/http/client_spec.rb

Fixes #521
Also move auto-deflate related code from `http/client.rb` to `http/features/auto_deflate.rb` which seems to be move appropriate place.

Skip auto-deflate when there is no body

---

lib/http/request/body.rb
spec/lib/http/request/body_spec.rb

Fix pipes support in bodies.

---

lib/http/response.rb
spec/lib/http/response_spec.rb

Require explicit MIME type for Respons#parse

---

lib/http/chainable.rb

This PR fixes this YARD warning:
```
lib/http/chainable.rb:171: [UnknownParam] @param tag has unknown parameter name: opts
```

Avoid YARD "UnknownTag" warning

---

.rubocop.yml
Gemfile
http.gemspec
lib/http/chainable.rb
lib/http/client.rb
lib/http/headers.rb
lib/http/mime_type/adapter.rb
lib/http/mime_type/json.rb
lib/http/options.rb
lib/http/redirector.rb
lib/http/request/body.rb
lib/http/request/writer.rb
lib/http/response/body.rb
lib/http/response/status.rb
lib/http/timeout/global.rb
lib/http/timeout/per_operation.rb
spec/lib/http/client_spec.rb
spec/lib/http/request/writer_spec.rb
spec/lib/http/request_spec.rb
spec/lib/http/response/status_spec.rb
spec/lib/http_spec.rb
spec/support/black_hole.rb
spec/support/dummy_server/servlet.rb
spec/support/ssl_helper.rb

I am trying to get more involved in open source code maintenance. In order to do this I figured I would try upgrading RuboCop for a few gems I use frequently to help them stay up to date. RuboCop on this project was very out of date so I started by upgrading it by ten minor versions to `0.59.2` but I can go further if the maintainers want.
I broke this PR into different commits based on what work I was doing. The first commit is the update and auto-fixes. The commits after that are the commits where I made judgement calls on what to do.
Please let me know if there's anything I can do to help or improve.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/httprb/http/548)

RuboCop upgrade

---

.rubocop.yml
Gemfile
lib/http/chainable.rb
lib/http/client.rb
lib/http/connection.rb
lib/http/content_type.rb
lib/http/features/auto_deflate.rb
lib/http/features/auto_inflate.rb
lib/http/headers.rb
lib/http/request.rb
lib/http/request/writer.rb
lib/http/uri.rb
spec/lib/http/connection_spec.rb
spec/lib/http/features/instrumentation_spec.rb
spec/lib/http/features/logging_spec.rb
spec/lib/http/options/merge_spec.rb
spec/lib/http/request_spec.rb
spec/support/dummy_server.rb
spec/support/http_handling_shared.rb
spec/support/ssl_helper.rb

In #548 I upgraded RuboCop by about 10 versions. In this PR I'm following up to upgrade to the latest version of RuboCop. All the changes in this PR are a result of the auto-correct flags so I didn't edit any code manually.
There are two specific items that I want to call out in this PR:
- First is that `rubocop-performance` is now its own gem that can be found here https://github.com/rubocop-hq/rubocop-performance. I suspect that we still want the performance cops to keep this project as performant as possible. Therefore I pulled the gem in and required the performance cops to keep them running. I tested to ensure that we are in fact still running performance cops.
- For Layout/AlignHash I had to make a call on which style to prefer. I personally like the table formatting, but I'm happy …

RuboCop upgrade 0.68 (latest)

---

lib/http/client.rb
lib/http/features/auto_inflate.rb
lib/http/response.rb
spec/lib/http/client_spec.rb
spec/lib/http/features/auto_inflate_spec.rb
spec/lib/http/features/instrumentation_spec.rb
spec/lib/http/features/logging_spec.rb
spec/lib/http/redirector_spec.rb
spec/lib/http/response_spec.rb

This fixes https://github.com/httprb/http/issues/463
This will greatly enhance the abilities of pluggable `Features` by
being able to reference the Request that initiated a Response. It will make it easy to solves issues like https://github.com/httprb/http/issues/545.
I wasn't very happy with all the changes to the specs to put a "fake" Request, but felt it was pretty important that the Request object be mandatory when creating a Response. If we left it optional, it might be too easy to create a new code path (like the `auto_inflate` code) that doesn't properly set the initiating Request. Open to suggestions.

Access the HTTP::Request from the HTTP::Response

---

lib/http/client.rb
lib/http/feature.rb
spec/lib/http/client_spec.rb

This addresses https://github.com/httprb/http/issues/547
It allows a Feature to implement an on_error handler so that it has a chance to react to Requests that never get a Response.

Allow Features to handle connection errors

---

CHANGES.md
lib/http/response.rb

Response initialize requires Request object now, making uri parsing absolutely redundant. And as it's a breaking change anyway - we should get rid of `:uri` option completely.
NOTE: We need to update WebMock's adapter to reflect this change prior releasing v5.0.0

Use Request#uri in Response

---

lib/http/chainable.rb
spec/lib/http_spec.rb

When `Hash` is passed to HTTP.timeout, it's been mutated. So when you pass
a frozen `Hash` it raises an exception.
Here is an example of the code:
```
timeout_settings = { connect: 5, write: 2, read: 10 }.freeze
HTTP.timeout(timeout_settings).get('http://example.com')
```
In this change, I have added a call to .dup on options Hash to create a
copy and avoid mutation of the original Hash.

Duplicate options Hash in .timeout call

---

lib/http/headers.rb
spec/lib/http/connection_spec.rb
spec/lib/http/headers_spec.rb
spec/lib/http/options/headers_spec.rb
spec/lib/http/request/writer_spec.rb

The original behavior was to normalize all header names so that they
were broken up into words, delimited by `-` or `_`, capitalize each word,
and then join the words together with a `-`.
This made it impossible to make a request with an underscore (`_`) in the header
name, or with a different casing (ex: all caps).
However, the normalized name made it possible to access (or delete) headers,
without having to know the exact casing.
The new behavior is based on the following rules (as specified in https://github.com/httprb/http/issues/524#issuecomment-460014322)
1) Fail if a header name is not specified as a String or Symbol
2) If the header name is specified as a Symbol, normalize it when writing it in a request.
If the header name is specified as a String, preserve it as-is when writing …

Preserve header casing as specified

---

lib/http/connection.rb
lib/http/features/auto_deflate.rb
lib/http/options.rb

In Ruby 2.7 `Nil#to_s` returns a frozen string, so we make sure to return a mutable string in `Connection#readpartial`, allowing it to be mutated in `Response::Body#to_s` (otherwise a `FrozenError` exception is raised). I thought about just returning `nil` instead, but I didn't want to break anything.
We also fix warnings around keyword arguments, as Ruby 2.7 wants us to be explicit about whether we're passing kwargs or hashes, as that will be the behaviour in Ruby 3.0.
Only one spec still fails, related to `http-form_data`, for which I've sent the PR in https://github.com/httprb/form_data/pull/28.
Btw, I also tried to see if we can replace CertificateAuthority with [Localhost](https://github.com/socketry/localhost) to remove the warnings, as the latter is much simpler and is actually …

Ruby 2.7 compatibility

---

README.md

https://github.com/tmm1/http_parser.rb isn't used since https://github.com/httprb/http/pull/489

Mention http-parser and FFI bindings in README

---

lib/http/redirector.rb
spec/lib/http/redirector_spec.rb

Fix redircetion with multiple Location headers

---

lib/http/response/parser.rb
spec/lib/http/response/parser_spec.rb

This patch adds support for 1XX informational responses. Those kinds of responses are sent along with normal responses, and flow looks like:
> GET / HTTP/1.1
> Host: example.com
>
< HTTP/1.1 100 Continue
< HTTP/1.1 200 OK
< Content-Length: 12
<
< Hello World!
Notice that server responds (sends to the socket) 2 HTTP responses.
---
Resolves: #592

Add info response support

---

README.md

Fairly self explanatory. Ruby 2.7.x is already being tested in Travis, but the `README` does not yet reflect that there is official support. 🙂

Reflect that Ruby 2.7.x is being tested on CI

---

.travis.yml

This PR updates the CI matrix to use latest JRuby, **9.2.11.0**.
[JRuby 9.2.11.0 release blog post](https://www.jruby.org/2020/03/02/jruby-9-2-11-0.html)

CI: Update to JRuby 9.2.11.0

---

lib/http/client.rb
lib/http/redirector.rb
lib/http/request.rb

As [mentioned](../issues/264#issuecomment-157070867) in #264, CookieJar
implements cookie domain scoping rules, which is useful when issuing
redirects across domains.
Resolves: #264

Use stateful CookieJar in Redirector

---

lib/http/response/inflater.rb
spec/lib/http_spec.rb
spec/support/dummy_server/servlet.rb

Hello,
This prevents the issue of Zlib::BufError errors raised when reading
by Inflater empty streams (should fix #624).
Thanks!

Inflater handle empty streams

---

lib/http/timeout/null.rb

I stumbled upon an issue where http.rb wouldn't respect the `verify_hostname` value of the current OpenSSL::SSL::SSLContext.
Previously we would unconditionally call [post_connection_check](https://github.com/ruby/openssl/blob/fd39183a61483c9b2b05aa5837a8185a522da653/lib/openssl/ssl.rb#L392), whose only purpose is to verify hostnames, regardless of what `verify_hostname` was set to. This results in quite a bit of user confusion since one expects hostname verification to be handled by OpenSSL itself rather than by the HTTP library.
Digging through the blames, it looks like this was never implemented properly. Ruby's Net::HTTP [fixed the same issue with this pull](https://github.com/ruby/ruby/pull/2858/commits/883693ce069c046c2e64e6449e5fb19660c8e21b#diff-a1d29a94def02829fd4f9ba591199acf079e …

Respect the SSL context's verify_hostname value

---

lib/http/timeout/null.rb

Following up on this comment:
https://github.com/httprb/http/pull/634#pullrequestreview-559142562
The previous logic skipped hostname verification entirely if the `verify_hostname` method is not defined for `OpenSSL::SSL::SSLContext`, which is currently the case for JRuby.
This commit changes the logic so if that method is undefined, hostname verification is still performed. Otherwise, hostname verification would always be skipped on Rubies which don't define a `verify_hostname` method.
Note that this was *just* introduced in #634 which was merged 10 hours ago, so I think this was caught quickly enough simply correcting it suffices and there isn't additional security-related followup here (e.g. CVE)

Make SSL hostname verification default to on

---

lib/http/request.rb

This is to support the RFC4791 Calendaring Extensions to WebDAV (aka, CalDAV), allowing a client to create a new calendar on a CalDAV server.

Add support for the MKCALENDAR HTTP verb

---

lib/http/client.rb
spec/lib/http/client_spec.rb

The change from 609f07b3454bde2f48ca5e1589cda169f7a77187 allows Features to handle errors, but it isn’t a complete implementation, because while it does handle read/write timeouts, it does not work for connection timeouts.
This pull request resolves this by moving connection establishment to the exception-handling block introduced in that commit.

Handle connection timeouts in Features

---

http.gemspec

Updates the `llhttp-ffi` dependency to `v0.3.0`. The only difference is that it now uses `lhttp v6.0.1`, the latest release.

Bump llhttp-ffi to 0.3.0

---

CHANGES.md

Drop of ruby 2.3.0 was already mentioned in CHANGES.md.  Drop of 2.4.0 was not, but 2.4.0 is in fact dropped in http release 5.0.0, and it should also be mentioned in changelog.

CHANGES mentions dropped ruby 2.4.0 support

---

lib/http/response.rb
spec/lib/http/response_spec.rb

Following the discussion in #665, this PR reverts the behavior of `Response#parse` to how it behaved in `4.x`.

Revert `Response#parse` behavior introduced in #540

---

lib/http/features/auto_inflate.rb
lib/http/response.rb
spec/lib/http/features/auto_inflate_spec.rb
spec/lib/http/features/instrumentation_spec.rb
spec/lib/http/features/logging_spec.rb
spec/lib/http/response_spec.rb

This should allow folks to update to 5.x without breaking code, in my case
test factories, which make HTTP::Responses.
If nothing else, the current code has the potential for `response.uri` and `response.request.uri` to be different and that seems Bad.
* Put :uri back, but its deprecated. Remove it in 6.x?
* :uri and :request now conflict to avoid having uri being one thing and request.uri another.
* Could allow it if uri and request.uri.to_s match?
* Is supplying both useful for forward compatibility?
* Remove redundant internal uses of uri.

feature: Restore HTTP::Response :uri option for backwards compatibility.

---

lib/http/response/body.rb
spec/lib/http/response/body_spec.rb

using the gem [Twitter](https://github.com/sferik/twitter), that uses this gem, we're receiving the bellow error:
This would have happened on this [PR](https://github.com/httprb/http/pull/344) when the strings inside of gem have became frozen also, and the problem was solved making test strings unfrozen.
This PR proposes to make the Response class deal with frozen strings.

Avoid force encoding on frozen strings

---

lib/http/request/writer.rb
spec/lib/http/request/writer_spec.rb

The HTTP spec says (https://tools.ietf.org/html/rfc7230#section-3.3.2):
> A user agent SHOULD NOT send a Content-Length header field when the request message does not contain a payload body and the method semantics do not anticipate such a body
Fixes https://github.com/httprb/http/issues/487.
This is my first time writing Ruby so hopefully the code isn't too bad :sweat_smile: happy to make changes.

Don't set Content-Length for GET, HEAD, DELETE, or CONNECT requests without a BODY

---

http.gemspec
lib/http/response/parser.rb

Resolves https://github.com/httprb/http/issues/685.
```
irb(main):004:0> HTTP.via('127.0.0.1', 8080).get('https://httpbin.org/get')
=> #<HTTP::Response/1.1 200 OK {"Date"=>"Thu, 09 Sep 2021 22:27:04 GMT", "Content-Type"=>"application/json", "Content-Length"=>"235", "Connection"=>"close", "Server"=>"gunicorn/19.9.0", "Access-Control-Allow-Origin"=>"*", "Access-Control-Allow-Credentials"=>"true"}>
```
I propose we include this as part of a 0.5.2 release.

Correctly reset the parser

---

lib/http/timeout/global.rb
lib/http/timeout/per_operation.rb

Hello there,
I want to add DNS failover support for the client.  
This implementation inclined with Nginx's behavior when used as a reverse proxy.
I need help adding the required specs; if someone wants to help, please send a pull request to my branch.
For some context, some services use [A records](https://en.wikipedia.org/wiki/List_of_DNS_record_types) with multiple IP addresses, unless you are large enough to handles failover at the [BGP](https://en.wikipedia.org/wiki/Border_Gateway_Protocol) level, this is the only practical way to eliminate a single point of failure.  
But the failover technique needs client support, hence the pull request.

DNS failover handling

---

lib/http/client.rb
spec/lib/http/client_spec.rb

When following redirects, features are not used for subsequent requests.
This makes it impossible to use automatic deflation after a redirect or to log and instrument redirected requests.
Wrap requests with configured features when following redirects.

Use features on redirected requests

---

lib/http/client.rb
spec/lib/http/client_spec.rb

When following redirects, features are not used for subsequent requests.
This makes it impossible to use automatic deflation after a redirect or to log and instrument redirected requests.
Wrap requests with configured features when following redirects.

Use features on redirected requests (4.x)

---

lib/http/request/writer.rb
spec/lib/http/request/writer_spec.rb

This prevents the issue of encoding errors when trying to concat binary
bodies with this header string.
This should resolve #490

Always encode headers as a binary string

---

Gemfile
lib/http/request/writer.rb
lib/http/timeout/global.rb
spec/lib/http/request/body_spec.rb

It seems we didn't have the rubocop version pinned before, and the latest version added new lints which we are failing.
The failures have been autocorrected.

Pin to rubocop v1.21; fix offenses

---

README.md

Small update to the README to remove note about 4.x now that 5.x is the stable branch.

Remove note about 5.x only being a dev branch now that its been released

---

lib/http/errors.rb
lib/http/timeout/global.rb
lib/http/timeout/per_operation.rb
spec/lib/http/client_spec.rb
spec/support/http_handling_shared.rb

HTTP.rb offers us a way of configuring open timeouts, but there is no way to tell which timeout is what from the caller's point of view.
In some scenarios such as systems prone to occasional network intermittencies, singling out a short connection timeout to retry specifically for that case is often desirable.  A catch-all retry strategy like we have today makes it hard to decide when to attempt a cheap and quick network intermittence retry from a long, target endpoint-health related write or read retry. 
I'm proposing we introduce `ConnectionTimeoutError` as a subclass of `TimeoutError` so it becomes possible for the user to selectively catch open-time specific timeouts while maintaining compatibility with catch-all code currently using `TimeoutError`.

Distinguish connection timeouts

---

spec/lib/http/redirector_spec.rb

There were two failures after merging #712 under the latest rubocop

Fix rubocop

---

lib/http/redirector.rb
spec/lib/http/redirector_spec.rb

Hello,
This adds an `on_redirect` callback that can be passed to `.follow`. For example:
```ruby
permanent_redirects = []
HTTP.follow(
max_hops: 4, 
on_redirect: proc do |from, to|
permanent_redirects.push({ from: from.uri.to_s, to: to.uri.to_s }) if [301, 308].include?(from.status.code)
end
).get("…")
```
I found this feature to be useful while trying to come up with a redirect caching system.
Thanks!

Add on_redirect callback.

---

CHANGES.md

Thanks everyone to their contributions to this gem. Really appreciate all the effort put in.
I've been in the middle of upgrading from 4.x to 5.x and I noticed an incorrect link in the change log. Fixed so it points to the correct link

Fixed incorrect link in CHANGES.md

---

lib/http/connection.rb
spec/lib/http/connection_spec.rb

When using persistent connections there is no easy way to check if the entire body of the previous request has been consumed before sending a new request, e.g. if an exception was raised while reading the body.
Add `Connection#finished?` which does the same check as the guards in `Connection#send_request`.
https://github.com/httprb/http/blob/32a2ae68a1650d267f0687381d58880cf1b60315/lib/http/connection.rb#L69-L76

Add `Connection#finished_request?`

---

http.gemspec

Updates the `llhttp-ffi` dependency to `v0.5.0`. The only difference is that it now uses `lhttp v8.1.0`, the latest release.

Bump llhttp-ffi (0.5.0)

---

lib/http/client.rb
spec/lib/http/client_spec.rb

Ran into an issue making requests to a server I don't control (Microsoft ASP.NET) where it was giving me errors POSTing JSON with `HTTP.post(path, json: {whatever})`. 
This header works: `Content-Type: application/json; charset=utf-8`
This did not: `Content-Type: application/json; charset=UTF-8`
HTTP.rb uses Ruby `String#encoding.name`, which returns "UTF" in all caps, which is causing the `charset=UTF-8`.
[MDN says "Case insensitive, lowercase preferred"](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type), so I just downcased the encoding name, and added a test.

Downcase Content-Type charset name

---

http.gemspec

This PR adds `base64` to runtime dependency to suppress the following Ruby 3.3's warning:
```console
$ ruby -wve 'require "http"'
ruby 3.3.0dev (2023-08-14T15:48:39Z master 52837fcec2) [x86_64-darwin22]
/Users/koic/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/http-5.1.1/lib/http/chainable.rb:3:
warning: base64 which will be not part of the default gems since Ruby 3.4.0
```
cf: https://github.com/rails/rails/pull/48907

Add `base64` to runtime dependency

---

spec/support/dummy_server/servlet.rb

If you request an unsupported URL from DummyServer, you get a 500 Internal Server Error instead of a 404 Not Found.
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
<HTML>
<HEAD><TITLE>Internal Server Error</TITLE></HEAD>
<BODY>
<H1>Internal Server Error</H1>
wrong number of arguments (given 0, expected 2)
<HR>
<ADDRESS>
WEBrick/1.8.1 (Ruby/3.2.2/2023-03-30) at
127.0.0.1:63416
</ADDRESS>
</BODY>
</HTML>
```

`DummyServer::Servlet#not_found` requires two arguments

---

lib/http/connection.rb
lib/http/timeout/null.rb
spec/lib/http/connection_spec.rb

When timeouts are set on the client, there is potential for a resource leak when timeouts occur during connection initialization.
When timeout errors are thrown during connection initialization, the connection object itself is not created (nil) and the [client](https://github.com/httprb/http/blob/main/lib/http/client.rb#L70) won't be able to properly close the connection. 
This causes the created socket to stay in either an ESTABLISHED or CLOSE_WAIT state, while the client no longer has a reference to it, effectively causing a leak.
Steps to repro:
In the client:
```ruby
client = HTTP.timeout(5)
client.get("https://www.example.org").body.to_s # or use 240.0.0.0
client.get("https://www.example.org").body.to_s
client.get("https://www.example.org").body.to_s
```
Simultaneously:
1. Set up a …

fix: close sockets on connection initialize timeout

---

lib/http/request.rb
spec/lib/http_spec.rb
spec/support/dummy_server/servlet.rb

If a custom URL normaliser does not filter out white-space, raise an exception to prevent CRLF injection. Whitespace, in particular `\n`, is never allowed in path, query or hostname.
This is not a security fix as such but an extra line of defence.

Prevent CRLF injection due to broken URL normalizer

---

lib/http/client.rb
spec/lib/http/client_spec.rb

Resolve https://github.com/httprb/http/issues/767
BREAKING CHANGE:
* multiple features execution depends on order, e.g. `HTTP.use(:auto_inflate, :logging)`
* [replay function in webmock](https://github.com/bblimke/webmock/blob/63940ac95345968cf435820a62102d913441862c/lib/webmock/http_lib_adapters/http_rb/webmock.rb#L46).

 Handle responses in the reverse order from the requests

---

lib/http/request.rb

This method is not defined in an RFC, but the HTTP RFC allows custom methods to be defined.
The `PURGE` method is often used in HTTP caching servers, for example:
- [Squid](https://wiki.squid-cache.org/SquidFaq/OperatingSquid#how-can-i-purge-an-object-from-my-cache)
- [Varnish](https://varnish-cache.org/docs/4.0/users-guide/purging.html)
- [Fastly](https://developer.fastly.com/learning/concepts/purging/#single-purge)

Add support for the `PURGE` HTTP method.

---

lib/http/errors.rb

Fixes comment typo in errors.rb

---

http.gemspec

Hi, I'm getting the following error when trying to use the HTTP gem with Rails 7.1.3:
```
You have already activated base64 0.1.1, but your Gemfile requires base64 0.2.0. Since base64 is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports base64 as a default gem. (Gem::LoadError)
```
RUBY VERSION
ruby 3.2.3p157
BUNDLED WITH
2.5.6
It looks like this will happen until ruby 3.4 when base64 is removed from the default gems. Since there weren't any API changes in the base64 gem since 0.1.1 despite the minor version update, it looks like this version is safe to bump: https://github.com/ruby/base64/releases.
I think removing the dependency like in #778 is preferable, but while that awaits review, we can bump the version here.

Update base64 dependency version

---

Gemfile
lib/http/chainable.rb
lib/http/response/status/reasons.rb
spec/support/proxy_server.rb

This is the minimum version that will bundle against our other dependencies.
I tried going to the latest version (1.65.0) but it added new lints whose autocorrections break the tests, so this should at least get the build green again.

Bump rubocop to v1.61

---

lib/http/connection.rb
lib/http/errors.rb
lib/http/request/writer.rb

- would love to have more granularity into what kind of Connection error is being thrown
- this PR changes 3/4 `ConnectionError` throws to use subclasses specific to that failure mode
- this is backwards compatible because they are subclasses of `ConnectionError` so this should not affect any existing `rescue` logic
- open to feedback!

Add more granularity to `ConnectionError` through more specific error classes

---

lib/http/chainable.rb
lib/http/errors.rb
lib/http/feature.rb
lib/http/features/raise_error.rb
spec/lib/http/features/raise_error_spec.rb

The library raises errors if the server does various unexpected things, e.g. `TooManyRedirectsError`, but it does not raise if the HTTP status code indicates a client error (4xx) or server (5xx) error.
Sometimes you are interested in non-successful responses, and sometimes you just want to treat them as any other error triggered by the server.
This PR adds a new feature that will raise an exception on status codes representing an error. If you want to skip this for specific codes, you can specify them in the `ignore` option.

New feature: RaiseError

---

lib/http/chainable.rb

This is purely a documentation fix for a typo in the comments for the `#retriable` method. The keyword argument was documented as `times` instead of `tries`.

Correct typo in comments for `retriable` method

---

lib/http/retriable/performer.rb

This fixes a circular require warning I encountered in [Peddler](https://github.com/lineofflight/peddler) when testing against the main branch of HTTP.rb.

Remove circular require

---

lib/http/errors.rb
lib/http/mime_type.rb
lib/http/response.rb
spec/lib/http/response_spec.rb

Closes https://github.com/httprb/http/issues/804

feat: introduce better error for wrong mime type

---

lib/http/headers.rb
lib/http/response.rb
spec/lib/http/headers_spec.rb
spec/lib/http/response_spec.rb

* Dumping all headers in `Headers#inspect` mostly useless
* Same about response, the only header part that is meaningfull there is MIME type
More importantly, Ruby-3.4 changed the inspect output, and we will either need to have if/else in specs, or modify the output to become ruby version-agnostic (i.e., not using Hash#inspect).
Blocks: https://github.com/httprb/http/pull/808

fix: Simplify response and headers inspection

---

.github/workflows/ci.yml
README.md

`Hash#inspect` output changed in Ruby-3.4 thus specs were failing. But even without that I don't think dumping all headers in `Response#inspect` was pointless, same about `Headers#inspect`.

Add ruby 3.4 support
